### ISSUE TITLE
Winnie the evolution of Platypus

### ISSUE THREAD

**Issue by Level0r0s** [marat-gainullin/winnie#11]
Winnie the evolution of Platypus
Good morning Marat
Winnie + Kenga is the evolution of Platypus?

**Comment by marat-gainullin** [comment]
Good morning.
Yes. Winnie + KengaJS + SeptimaJS combination is an evolution of Platypus.js ideas. They are fully reimplemented with modern tech stack involving es6, minification / obfuscation, promises, etc. And on the server side there is Java code (https://github.com/marat-gainullin/septima) with support of latest servlet specification with non-blocking reading and writing of http requests, static typing of model's entities, etc.
